---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 10.34.4
  # require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[repro::default]
    attributes:
      repro:
        config:
          instances:
            - host: localhost
              port: 9999
              extra_key: extra_val
              conf:
                - include:
                    domain: domain0
                    type: ThreadPool
                    bean: tomcat_bean
                    attributes:
                      maxThreads:
                        alias: tomcat.threads.max
                        metric_type: gauge
                      bytesReceived:
                        alias: tomcat.bytes_rcvd
                        metric_type: counter
                  include:
                    domain: org.apache.cassandra.db
                    attributes:
                      - BloomFilterDiskSpaceUsed
                      - Capacity
                    bean_name: com.datadoghq.test:type=BeanType,tag1=my_bean_name
                    foo: bar
                  exclude:
                  - domain: evil_domain
